// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Shoutr.Serialization {

  /// <summary>Holder for reflection information generated from ProtoMessage.proto</summary>
  public static partial class ProtoMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQcm90b01lc3NhZ2UucHJvdG8SBnNob3V0ciKiAgoMUHJvdG9NZXNzYWdl",
            "EhgKC0Jyb2FkY2FzdElkGAEgASgMSACIAQESGQoMUGF5bG9hZEluZGV4GAIg",
            "ASgDSAGIAQESFAoHUGF5bG9hZBgDIAEoDEgCiAEBEhsKDlBheWxvYWRNYXhT",
            "aXplGAQgASgDSAOIAQESFQoIRmlsZU5hbWUYBSABKAlIBIgBARIZCgxQYXls",
            "b2FkQ291bnQYBiABKANIBYgBARIRCgRIYXNoGAcgASgMSAaIAQFCDgoMX0Jy",
            "b2FkY2FzdElkQg8KDV9QYXlsb2FkSW5kZXhCCgoIX1BheWxvYWRCEQoPX1Bh",
            "eWxvYWRNYXhTaXplQgsKCV9GaWxlTmFtZUIPCg1fUGF5bG9hZENvdW50QgcK",
            "BV9IYXNoQheqAhRTaG91dHIuU2VyaWFsaXphdGlvbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Shoutr.Serialization.ProtoMessage), global::Shoutr.Serialization.ProtoMessage.Parser, new[]{ "BroadcastId", "PayloadIndex", "Payload", "PayloadMaxSize", "FileName", "PayloadCount", "Hash" }, new[]{ "BroadcastId", "PayloadIndex", "Payload", "PayloadMaxSize", "FileName", "PayloadCount", "Hash" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtoMessage : pb::IMessage<ProtoMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoMessage> _parser = new pb::MessageParser<ProtoMessage>(() => new ProtoMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Shoutr.Serialization.ProtoMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMessage(ProtoMessage other) : this() {
      _hasBits0 = other._hasBits0;
      broadcastId_ = other.broadcastId_;
      payloadIndex_ = other.payloadIndex_;
      payload_ = other.payload_;
      payloadMaxSize_ = other.payloadMaxSize_;
      fileName_ = other.fileName_;
      payloadCount_ = other.payloadCount_;
      hash_ = other.hash_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoMessage Clone() {
      return new ProtoMessage(this);
    }

    /// <summary>Field number for the "BroadcastId" field.</summary>
    public const int BroadcastIdFieldNumber = 1;
    private readonly static pb::ByteString BroadcastIdDefaultValue = pb::ByteString.Empty;

    private pb::ByteString broadcastId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BroadcastId {
      get { return broadcastId_ ?? BroadcastIdDefaultValue; }
      set {
        broadcastId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "BroadcastId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBroadcastId {
      get { return broadcastId_ != null; }
    }
    /// <summary>Clears the value of the "BroadcastId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBroadcastId() {
      broadcastId_ = null;
    }

    /// <summary>Field number for the "PayloadIndex" field.</summary>
    public const int PayloadIndexFieldNumber = 2;
    private readonly static long PayloadIndexDefaultValue = 0L;

    private long payloadIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PayloadIndex {
      get { if ((_hasBits0 & 1) != 0) { return payloadIndex_; } else { return PayloadIndexDefaultValue; } }
      set {
        _hasBits0 |= 1;
        payloadIndex_ = value;
      }
    }
    /// <summary>Gets whether the "PayloadIndex" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPayloadIndex {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "PayloadIndex" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayloadIndex() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "Payload" field.</summary>
    public const int PayloadFieldNumber = 3;
    private readonly static pb::ByteString PayloadDefaultValue = pb::ByteString.Empty;

    private pb::ByteString payload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Payload {
      get { return payload_ ?? PayloadDefaultValue; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Payload" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPayload {
      get { return payload_ != null; }
    }
    /// <summary>Clears the value of the "Payload" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payload_ = null;
    }

    /// <summary>Field number for the "PayloadMaxSize" field.</summary>
    public const int PayloadMaxSizeFieldNumber = 4;
    private readonly static long PayloadMaxSizeDefaultValue = 0L;

    private long payloadMaxSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PayloadMaxSize {
      get { if ((_hasBits0 & 2) != 0) { return payloadMaxSize_; } else { return PayloadMaxSizeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        payloadMaxSize_ = value;
      }
    }
    /// <summary>Gets whether the "PayloadMaxSize" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPayloadMaxSize {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "PayloadMaxSize" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayloadMaxSize() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "FileName" field.</summary>
    public const int FileNameFieldNumber = 5;
    private readonly static string FileNameDefaultValue = "";

    private string fileName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileName {
      get { return fileName_ ?? FileNameDefaultValue; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "FileName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFileName {
      get { return fileName_ != null; }
    }
    /// <summary>Clears the value of the "FileName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFileName() {
      fileName_ = null;
    }

    /// <summary>Field number for the "PayloadCount" field.</summary>
    public const int PayloadCountFieldNumber = 6;
    private readonly static long PayloadCountDefaultValue = 0L;

    private long payloadCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PayloadCount {
      get { if ((_hasBits0 & 4) != 0) { return payloadCount_; } else { return PayloadCountDefaultValue; } }
      set {
        _hasBits0 |= 4;
        payloadCount_ = value;
      }
    }
    /// <summary>Gets whether the "PayloadCount" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPayloadCount {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "PayloadCount" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayloadCount() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "Hash" field.</summary>
    public const int HashFieldNumber = 7;
    private readonly static pb::ByteString HashDefaultValue = pb::ByteString.Empty;

    private pb::ByteString hash_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Hash {
      get { return hash_ ?? HashDefaultValue; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Hash" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHash {
      get { return hash_ != null; }
    }
    /// <summary>Clears the value of the "Hash" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHash() {
      hash_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BroadcastId != other.BroadcastId) return false;
      if (PayloadIndex != other.PayloadIndex) return false;
      if (Payload != other.Payload) return false;
      if (PayloadMaxSize != other.PayloadMaxSize) return false;
      if (FileName != other.FileName) return false;
      if (PayloadCount != other.PayloadCount) return false;
      if (Hash != other.Hash) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBroadcastId) hash ^= BroadcastId.GetHashCode();
      if (HasPayloadIndex) hash ^= PayloadIndex.GetHashCode();
      if (HasPayload) hash ^= Payload.GetHashCode();
      if (HasPayloadMaxSize) hash ^= PayloadMaxSize.GetHashCode();
      if (HasFileName) hash ^= FileName.GetHashCode();
      if (HasPayloadCount) hash ^= PayloadCount.GetHashCode();
      if (HasHash) hash ^= Hash.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasBroadcastId) {
        output.WriteRawTag(10);
        output.WriteBytes(BroadcastId);
      }
      if (HasPayloadIndex) {
        output.WriteRawTag(16);
        output.WriteInt64(PayloadIndex);
      }
      if (HasPayload) {
        output.WriteRawTag(26);
        output.WriteBytes(Payload);
      }
      if (HasPayloadMaxSize) {
        output.WriteRawTag(32);
        output.WriteInt64(PayloadMaxSize);
      }
      if (HasFileName) {
        output.WriteRawTag(42);
        output.WriteString(FileName);
      }
      if (HasPayloadCount) {
        output.WriteRawTag(48);
        output.WriteInt64(PayloadCount);
      }
      if (HasHash) {
        output.WriteRawTag(58);
        output.WriteBytes(Hash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasBroadcastId) {
        output.WriteRawTag(10);
        output.WriteBytes(BroadcastId);
      }
      if (HasPayloadIndex) {
        output.WriteRawTag(16);
        output.WriteInt64(PayloadIndex);
      }
      if (HasPayload) {
        output.WriteRawTag(26);
        output.WriteBytes(Payload);
      }
      if (HasPayloadMaxSize) {
        output.WriteRawTag(32);
        output.WriteInt64(PayloadMaxSize);
      }
      if (HasFileName) {
        output.WriteRawTag(42);
        output.WriteString(FileName);
      }
      if (HasPayloadCount) {
        output.WriteRawTag(48);
        output.WriteInt64(PayloadCount);
      }
      if (HasHash) {
        output.WriteRawTag(58);
        output.WriteBytes(Hash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasBroadcastId) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BroadcastId);
      }
      if (HasPayloadIndex) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PayloadIndex);
      }
      if (HasPayload) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (HasPayloadMaxSize) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PayloadMaxSize);
      }
      if (HasFileName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (HasPayloadCount) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PayloadCount);
      }
      if (HasHash) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Hash);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoMessage other) {
      if (other == null) {
        return;
      }
      if (other.HasBroadcastId) {
        BroadcastId = other.BroadcastId;
      }
      if (other.HasPayloadIndex) {
        PayloadIndex = other.PayloadIndex;
      }
      if (other.HasPayload) {
        Payload = other.Payload;
      }
      if (other.HasPayloadMaxSize) {
        PayloadMaxSize = other.PayloadMaxSize;
      }
      if (other.HasFileName) {
        FileName = other.FileName;
      }
      if (other.HasPayloadCount) {
        PayloadCount = other.PayloadCount;
      }
      if (other.HasHash) {
        Hash = other.Hash;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BroadcastId = input.ReadBytes();
            break;
          }
          case 16: {
            PayloadIndex = input.ReadInt64();
            break;
          }
          case 26: {
            Payload = input.ReadBytes();
            break;
          }
          case 32: {
            PayloadMaxSize = input.ReadInt64();
            break;
          }
          case 42: {
            FileName = input.ReadString();
            break;
          }
          case 48: {
            PayloadCount = input.ReadInt64();
            break;
          }
          case 58: {
            Hash = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BroadcastId = input.ReadBytes();
            break;
          }
          case 16: {
            PayloadIndex = input.ReadInt64();
            break;
          }
          case 26: {
            Payload = input.ReadBytes();
            break;
          }
          case 32: {
            PayloadMaxSize = input.ReadInt64();
            break;
          }
          case 42: {
            FileName = input.ReadString();
            break;
          }
          case 48: {
            PayloadCount = input.ReadInt64();
            break;
          }
          case 58: {
            Hash = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
